### PR TITLE
reorder analyses

### PR DESCRIPTION
**Pull request by chrisgorgo**
I assume you want `session` level to be run before `participant`.

### CODE REVIEW

**Comment by gkiar** [comment]
Is the way the driver is currently working expecting the analysis levels to be in order, and that's how it interprets whether multiple participant or group level stages are to be run? I.e. `[participant, group, participant, group]`?

**Comment by chrisgorgo** [comment]
Yes. 

In addition names of levels should be unique. So your example should be `[participant1, group1, participant2, group2]`

**Comment by gkiar** [comment]
Thanks for the PR! I actually don't have participant level, just `["session", "group"]`. Once my app passes tests (I hope it will this time) I'll merge your PR.

**Comment by chrisgorgo** [comment]
Interesting. Since OpenNeuro does not support "session" level yet we should
make sure the right version of ndmg is deployed. Which one was the last to
support "participant" level?

Best,
Chris

**Comment by gkiar** [comment]
I'm not certain that the last version which supported participant level didn't have a broken group level API. I may just write a wrapper script for the time being that converts the "participant" argument to "session" in my command-line arg.

**Comment by gkiar** [comment]
OK so I've updated my API to interpret participant and session the same way - and specify both `--participant_label` and `--session_label` flags. For platforms such as OpenNeuro, this should be fine since they'll say `participant` and ignore the session flag, but if we leave the Boutiques descriptor as `["session", "group"]`, then future apps which will work with this interpretation can natively support this analysis level.

Actionably on this PR, that means we should just update that line you changed to be as stated above, I think.

**Comment by chrisgorgo** [comment]
Done!

Life will be so much better with CBRAIN and boutiques :)

**Review by gkiar — APPROVED** [review]

**Comment by gkiar** [comment]
:) Thanks for the PR!

**Pull request merged**
